---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-todo
  labels:
    app: simple-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-todo
  template:
    metadata:
      labels:
        app: simple-todo
    spec:
      containers:
      - name: simple-todo
        image: node:18-alpine
        command: ["/bin/sh"]
        args: ["-c", "echo '<!DOCTYPE html><html><head><title>Simple Todo App</title><style>body{font-family:Arial;margin:40px;}.container{max-width:800px;margin:0 auto;}.todo{background:#f9f9f9;padding:20px;margin:10px 0;border-radius:5px;}</style></head><body><div class=container><h1>Simple Todo Application</h1><div class=todo><h3>✓ Deployed on Kubernetes</h3><p>Running on: <span id=hostname></span></p><p>Pod IP: <span id=pod-ip></span></p><p>Node: <span id=node-name></span></p></div></div><script>fetch(/etc/hostname).then(r=>r.text().then(h=>document.getElementById(\"hostname\").textContent=h));fetch(\"http://169.254.169.254/latest/meta-data/local-ipv4\").then(r=>r.text().then(ip=>document.getElementById(\"pod-ip\").textContent=ip));fetch(\"http://169.254.169.254/latest/meta-data/hostname\").then(r=>r.text().then(node=>document.getElementById(\"node-name\").textContent=node));</script></body></html>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-todo-service
spec:
  selector:
    app: simple-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30200
  type: NodePort
